USER_24_PUBLIC__22snowflake_dbt_22:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DEMO
      schema: DBT_JAVI
    prod:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DEMO
      schema: DBT_JAVI_PROD

